default-group: local
openapi: ../openapi.json
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.7.2
        output:
          location: local-file-system
          path: ../../packages/typescript/src
        config: 
          namespaceExport: owlebot
          timeoutInSeconds: 120
          noSerdeLayer: true
          outputEsm: true
