app:
  name: open-api
  platform: default
  image: registry.gitlab.com/owlebot/docker-registry/open-api
  replicas: 1

ingress:
  enabled: true
  host: api.owle.bot

health:
  enabled: true
  endpoint: "/health"

infisical:
  path: /open-api
  env: prod
